In [12]:
import pandas as pd

def convert_dataframe(df):
    # Function to convert CAN_ID fields to a hex string
    def convert_can_id(row):
        binary_string = ''.join([str(int(row[f'CAN_ID_{i}'])) for i in range(11)])
        return '{:04x}'.format(int(binary_string, 2))

    # Function to convert DATA fields based on DLC
    def convert_data(row):
        bits_to_consider = int(row['DLC']) * 8
        data_bits = ''.join([str(int(row[f'DATA_{i}'])) for i in range(bits_to_consider)])
        return [f'{int(data_bits[i:i+8], 2):02x}' for i in range(0, len(data_bits), 8)]

    # Create a new dataframe for the converted data
    converted_df = pd.DataFrame()
    converted_df['Timestamp'] = df['Timestamp']
    converted_df['CAN_ID_HEX'] = df.apply(convert_can_id, axis=1)
    
    # Convert DATA fields
    data_transformed = df.apply(convert_data, axis=1).tolist()
    for i in range(8):
        converted_df[f'DATA_{i}'] = [item[i] if i < len(item) else '' for item in data_transformed]

    # Copy the Label column
    converted_df['Label'] = df['Label']

    return converted_df

# Example usage
# converted_df = convert_dataframe('path_to_your_csv_file.csv')

In [27]:
df = pd.read_csv("../data_selected/car_hacking/DoS_dataset_aligned_train_bits.csv", nrows=50)
converted_df = convert_dataframe(df)
converted_df
# converted_df.to_csv("test.csv", index=False)

,Timestamp,CAN_ID_HEX,DATA_0,DATA_1,DATA_2,DATA_3,DATA_4,DATA_5,DATA_6,DATA_7,Label
0,1.478198e+09,018f,fe,5b,00,00,00,3c,00,00,R
1,1.478198e+09,0260,19,21,22,30,08,8e,6d,3a,R
2,1.478198e+09,0130,08,80,00,ff,31,80,0b,7f,R
3,1.478198e+09,0140,00,00,00,00,08,22,2b,a3,R
4,1.478198e+09,02a0,04,00,9a,1d,97,02,bd,00,R
5,1.478198e+09,04b1,29,27,27,23,00,00,00,9a,R
6,1.478198e+09,0350,05,20,24,68,77,00,00,1e,R
7,1.478198e+09,0130,0b,80,00,ff,45,80,0c,85,R
8,1.478198e+09,0370,00,20,00,00,00,00,00,00,R
9,1.478198e+09,0440,ff,00,00,00,ff,cd,08,00,R
10,1.478198e+09,0316,05,21,68,09,21,21,00,6f,R
11,1.478198e+09,02c0,14,00,00,00,00,00,00,00,R
12,1.478198e+09,0350,05,20,44,68,76,00,00,7f,R
13,1.478198e+09,0370,00,20,00,00,00,00,00,00,R
14,1.478198e+09,0440,ff,00,00,00,ff,ca,08,00,R
15,1.478198e+09,0329,40,bb,7f,14,11,20,00,14,R
16,1.478198e+09,0440,ff,00,00,00,ff,c9,08,00,R
17,1.478198e+09,0260,19,22,22,30,08,8e,71,03,R
18,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
19,1.478198e+09,02c0,14,00,00,00,00,00,00,00,R
20,1.478198e+09,0131,0e,80,00,00,55,7f,00,d2,R
21,1.478198e+09,0316,05,22,60,09,22,21,00,6f,R
22,1.478198e+09,02a0,24,00,9a,1d,97,02,bd,00,R
23,1.478198e+09,0002,00,00,00,00,00,03,01,c3,R
24,1.478198e+09,0440,ff,00,00,00,ff,c9,08,00,R
25,1.478198e+09,0260,19,22,22,30,08,8e,70,26,R
26,1.478198e+09,02a0,44,00,9a,1d,97,02,bd,00,R
27,1.478198e+09,05f0,01,00,,,,,,,R
28,1.478198e+09,01f1,08,00,00,00,00,00,00,00,R
29,1.478198e+09,0329,86,bb,7f,14,11,20,00,14,R
30,1.478198e+09,0002,00,00,00,00,00,03,03,f9,R
31,1.478198e+09,0350,05,20,94,68,77,00,00,ae,R
32,1.478198e+09,04b1,29,27,27,23,00,00,00,9a,R
33,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
34,1.478198e+09,0350,05,20,a4,68,77,00,00,9e,R
35,1.478198e+09,0130,12,80,00,ff,0e,80,04,bb,R
36,1.478198e+09,0316,05,21,68,09,21,21,00,6f,R
37,1.478198e+09,0260,19,21,22,30,08,8e,6e,17,R
38,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
39,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
40,1.478198e+09,0316,05,21,68,09,21,21,00,6f,R
41,1.478198e+09,0370,00,20,00,00,00,00,00,00,R
42,1.478198e+09,04f0,00,00,00,80,00,69,d1,13,R
43,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
44,1.478198e+09,0002,00,00,00,00,00,04,08,cf,R
45,1.478198e+09,0140,00,00,00,00,08,20,28,1c,R
46,1.478198e+09,0131,e5,7f,00,00,18,7f,09,ee,R
47,1.478198e+09,043f,00,40,60,ff,7e,c4,08,00,R
48,1.478198e+09,0316,05,22,60,09,22,21,00,6f,R
49,1.478198e+09,018f,fe,5b,00,00,00,3c,00,00,R

In [18]:
raw_df = pd.read_csv("../data_selected/car_hacking/DoS_dataset_aligned_train.csv", nrows=50)
raw_df

,Timestamp,CAN_ID,DLC,DATA_0,DATA_1,DATA_2,DATA_3,DATA_4,DATA_5,DATA_6,DATA_7,Label
0,1.478198e+09,018f,8,fe,5b,00,00,00,3c,00,00,R
1,1.478198e+09,0260,8,19,21,22,30,08,8e,6d,3a,R
2,1.478198e+09,0130,8,08,80,00,ff,31,80,0b,7f,R
3,1.478198e+09,0140,8,00,00,00,00,08,22,2b,a3,R
4,1.478198e+09,02a0,8,04,00,9a,1d,97,02,bd,00,R
5,1.478198e+09,04b1,8,29,27,27,23,00,00,00,9a,R
6,1.478198e+09,0350,8,05,20,24,68,77,00,00,1e,R
7,1.478198e+09,0130,8,0b,80,00,ff,45,80,0c,85,R
8,1.478198e+09,0370,8,00,20,00,00,00,00,00,00,R
9,1.478198e+09,0440,8,ff,00,00,00,ff,cd,08,00,R
10,1.478198e+09,0316,8,05,21,68,09,21,21,00,6f,R
11,1.478198e+09,02c0,8,14,00,00,00,00,00,00,00,R
12,1.478198e+09,0350,8,05,20,44,68,76,00,00,7f,R
13,1.478198e+09,0370,8,00,20,00,00,00,00,00,00,R
14,1.478198e+09,0440,8,ff,00,00,00,ff,ca,08,00,R
15,1.478198e+09,0329,8,40,bb,7f,14,11,20,00,14,R
16,1.478198e+09,0440,8,ff,00,00,00,ff,c9,08,00,R
17,1.478198e+09,0260,8,19,22,22,30,08,8e,71,03,R
18,1.478198e+09,0153,8,00,21,10,ff,00,ff,00,00,R
19,1.478198e+09,02c0,8,14,00,00,00,00,00,00,00,R
20,1.478198e+09,0131,8,0e,80,00,00,55,7f,00,d2,R
21,1.478198e+09,0316,8,05,22,60,09,22,21,00,6f,R
22,1.478198e+09,02a0,8,24,00,9a,1d,97,02,bd,00,R
23,1.478198e+09,0002,8,00,00,00,00,00,03,01,c3,R
24,1.478198e+09,0440,8,ff,00,00,00,ff,c9,08,00,R
25,1.478198e+09,0260,8,19,22,22,30,08,8e,70,26,R
26,1.478198e+09,02a0,8,44,00,9a,1d,97,02,bd,00,R
27,1.478198e+09,05f0,2,01,00,NaN,NaN,NaN,NaN,NaN,NaN,R
28,1.478198e+09,01f1,8,08,00,00,00,00,00,00,00,R
29,1.478198e+09,0329,8,86,bb,7f,14,11,20,00,14,R
30,1.478198e+09,0002,8,00,00,00,00,00,03,03,f9,R
31,1.478198e+09,0350,8,05,20,94,68,77,00,00,ae,R
32,1.478198e+09,04b1,8,29,27,27,23,00,00,00,9a,R
33,1.478198e+09,0153,8,00,21,10,ff,00,ff,00,00,R
34,1.478198e+09,0350,8,05,20,a4,68,77,00,00,9e,R
35,1.478198e+09,0130,8,12,80,00,ff,0e,80,04,bb,R
36,1.478198e+09,0316,8,05,21,68,09,21,21,00,6f,R
37,1.478198e+09,0260,8,19,21,22,30,08,8e,6e,17,R
38,1.478198e+09,0153,8,00,21,10,ff,00,ff,00,00,R
39,1.478198e+09,0153,8,00,21,10,ff,00,ff,00,00,R
40,1.478198e+09,0316,8,05,21,68,09,21,21,00,6f,R
41,1.478198e+09,0370,8,00,20,00,00,00,00,00,00,R
42,1.478198e+09,04f0,8,00,00,00,80,00,69,d1,13,R
43,1.478198e+09,0153,8,00,21,10,ff,00,ff,00,00,R
44,1.478198e+09,0002,8,00,00,00,00,00,04,08,cf,R
45,1.478198e+09,0140,8,00,00,00,00,08,20,28,1c,R
46,1.478198e+09,0131,8,e5,7f,00,00,18,7f,09,ee,R
47,1.478198e+09,043f,8,00,40,60,ff,7e,c4,08,00,R
48,1.478198e+09,0316,8,05,22,60,09,22,21,00,6f,R
49,1.478198e+09,018f,8,fe,5b,00,00,00,3c,00,00,R

In [22]:
df = pd.read_csv("test.csv")

In [23]:
df

,Timestamp,CAN_ID_HEX,DATA_0,DATA_1,DATA_2,DATA_3,DATA_4,DATA_5,DATA_6,DATA_7,Label
0,1.478198e+09,018f,fe,5b,00,00,00,3c,00,00,R
1,1.478198e+09,0260,19,21,22,30,08,8e,6d,3a,R
2,1.478198e+09,0130,08,80,00,ff,31,80,0b,7f,R
3,1.478198e+09,0140,00,00,00,00,08,22,2b,a3,R
4,1.478198e+09,02a0,04,00,9a,1d,97,02,bd,00,R
5,1.478198e+09,04b1,29,27,27,23,00,00,00,9a,R
6,1.478198e+09,0350,05,20,24,68,77,00,00,1e,R
7,1.478198e+09,0130,0b,80,00,ff,45,80,0c,85,R
8,1.478198e+09,0370,00,20,00,00,00,00,00,00,R
9,1.478198e+09,0440,ff,00,00,00,ff,cd,08,00,R
10,1.478198e+09,0316,05,21,68,09,21,21,00,6f,R
11,1.478198e+09,02c0,14,00,00,00,00,00,00,00,R
12,1.478198e+09,0350,05,20,44,68,76,00,00,7f,R
13,1.478198e+09,0370,00,20,00,00,00,00,00,00,R
14,1.478198e+09,0440,ff,00,00,00,ff,ca,08,00,R
15,1.478198e+09,0329,40,bb,7f,14,11,20,00,14,R
16,1.478198e+09,0440,ff,00,00,00,ff,c9,08,00,R
17,1.478198e+09,0260,19,22,22,30,08,8e,71,03,R
18,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
19,1.478198e+09,02c0,14,00,00,00,00,00,00,00,R
20,1.478198e+09,0131,0e,80,00,00,55,7f,00,d2,R
21,1.478198e+09,0316,05,22,60,09,22,21,00,6f,R
22,1.478198e+09,02a0,24,00,9a,1d,97,02,bd,00,R
23,1.478198e+09,0002,00,00,00,00,00,03,01,c3,R
24,1.478198e+09,0440,ff,00,00,00,ff,c9,08,00,R
25,1.478198e+09,0260,19,22,22,30,08,8e,70,26,R
26,1.478198e+09,02a0,44,00,9a,1d,97,02,bd,00,R
27,1.478198e+09,05f0,01,00,NaN,NaN,NaN,NaN,NaN,NaN,R
28,1.478198e+09,01f1,08,00,00,00,00,00,00,00,R
29,1.478198e+09,0329,86,bb,7f,14,11,20,00,14,R
30,1.478198e+09,0002,00,00,00,00,00,03,03,f9,R
31,1.478198e+09,0350,05,20,94,68,77,00,00,ae,R
32,1.478198e+09,04b1,29,27,27,23,00,00,00,9a,R
33,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
34,1.478198e+09,0350,05,20,a4,68,77,00,00,9e,R
35,1.478198e+09,0130,12,80,00,ff,0e,80,04,bb,R
36,1.478198e+09,0316,05,21,68,09,21,21,00,6f,R
37,1.478198e+09,0260,19,21,22,30,08,8e,6e,17,R
38,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
39,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
40,1.478198e+09,0316,05,21,68,09,21,21,00,6f,R
41,1.478198e+09,0370,00,20,00,00,00,00,00,00,R
42,1.478198e+09,04f0,00,00,00,80,00,69,d1,13,R
43,1.478198e+09,0153,00,21,10,ff,00,ff,00,00,R
44,1.478198e+09,0002,00,00,00,00,00,04,08,cf,R
45,1.478198e+09,0140,00,00,00,00,08,20,28,1c,R
46,1.478198e+09,0131,e5,7f,00,00,18,7f,09,ee,R
47,1.478198e+09,043f,00,40,60,ff,7e,c4,08,00,R
48,1.478198e+09,0316,05,22,60,09,22,21,00,6f,R
49,1.478198e+09,018f,fe,5b,00,00,00,3c,00,00,R